name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build_container_image:
    name: 'Build Container Image'
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: semver
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: ${{ !(github.ref == 'refs/heads/main' && github.event_name == 'push') }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:lambda/src/VanLaw.Dev.TeslaLambda.Function"
          push: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') }}
          tags: |
            ghcr.io/cvanlaw/tesla-data-exporter:latest